const express =  require('express');
const router =  express.Router();
router.use('/desktop/auth',require('./auth'));
router.use(require('./disponibiliteRoutes'));
router.use(require('./ToDoRoutes'));
router.use(require('./Chat_messageRoutes'));
router.use(require('./Chat_groupRoutes'));
router.use(require('./colisRoutes'));
router.use(require('./retraitRoutes'));
router.use(require('./depotRoutes'));
router.use(require('./bilanRoutes'));
router.use(require('./caisseRoutes'));
router.use(require('./caveauxRoutes'));
router.use(require('./partenaireRoutes'));
router.use(require('./agenceRoutes'));
router.use(require('./transfertRoutes'));
router.use(require('./codeMoneyRoutes'));
router.use(require('./qrcodeRoutes'));
router.use(require('./cityRoutes'));
router.use(require('./regionRoutes'));
router.use(require('./countryRoutes'));
router.use(require('./userRoutes'));
router.use(require('./roleRoutes'));
router.use(require('./projectRouteRoutes'));
router.use(require('./routeRoleRoutes'));
router.use(require('./userRoleRoutes'));
router.use(require('./uploadRoutes'));

module.exports = router;
